
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router";



const About = lazy(() => import("./pages/About.tsx"));
const Admin = lazy(() => import("./pages/Admin.tsx"));
const AdminLogin = lazy(() => import("./pages/AdminLogin.tsx"));
const AdminPanel = lazy(() => import("./pages/AdminPanel.tsx"));
const App = lazy(() => import("./pages/App.tsx"));
const Cart = lazy(() => import("./pages/Cart.tsx"));
const Categories = lazy(() => import("./pages/Categories.tsx"));
const Checkout = lazy(() => import("./pages/Checkout.tsx"));
const Contact = lazy(() => import("./pages/Contact.tsx"));
const DeploymentGuide = lazy(() => import("./pages/DeploymentGuide.tsx"));
const Favorites = lazy(() => import("./pages/Favorites.tsx"));
const MyOrders = lazy(() => import("./pages/MyOrders.tsx"));
const Order = lazy(() => import("./pages/Order.tsx"));
const OrderConfirmation = lazy(() => import("./pages/OrderConfirmation.tsx"));
const OrderPrint = lazy(() => import("./pages/OrderPrint.tsx"));
const Orders = lazy(() => import("./pages/Orders.tsx"));
const Product = lazy(() => import("./pages/Product.tsx"));
const Profile = lazy(() => import("./pages/Profile.tsx"));
const Search = lazy(() => import("./pages/Search.tsx"));
const Shop = lazy(() => import("./pages/Shop.tsx"));
const SignIn = lazy(() => import("./pages/SignIn.tsx"));
const SignUp = lazy(() => import("./pages/SignUp.tsx"));
const SupplierDashboard = lazy(() => import("./pages/SupplierDashboard.tsx"));
const SupplierProductAdd = lazy(() => import("./pages/SupplierProductAdd.tsx"));
const SupplierProductEdit = lazy(() => import("./pages/SupplierProductEdit.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/about", element: <About />},
	{ path: "/admin", element: <Admin />},
	{ path: "/admin-login", element: <AdminLogin />},
	{ path: "/adminlogin", element: <AdminLogin />},
	{ path: "/admin-panel", element: <AdminPanel />},
	{ path: "/adminpanel", element: <AdminPanel />},
	{ path: "/", element: <App />},
	{ path: "/cart", element: <Cart />},
	{ path: "/categories", element: <Categories />},
	{ path: "/checkout", element: <Checkout />},
	{ path: "/contact", element: <Contact />},
	{ path: "/deployment-guide", element: <DeploymentGuide />},
	{ path: "/deploymentguide", element: <DeploymentGuide />},
	{ path: "/favorites", element: <Favorites />},
	{ path: "/my-orders", element: <MyOrders />},
	{ path: "/myorders", element: <MyOrders />},
	{ path: "/order", element: <Order />},
	{ path: "/order-confirmation", element: <OrderConfirmation />},
	{ path: "/orderconfirmation", element: <OrderConfirmation />},
	{ path: "/order-print", element: <OrderPrint />},
	{ path: "/orderprint", element: <OrderPrint />},
	{ path: "/orders", element: <Orders />},
	{ path: "/product", element: <Product />},
	{ path: "/profile", element: <Profile />},
	{ path: "/search", element: <Search />},
	{ path: "/shop", element: <Shop />},
	{ path: "/sign-in", element: <SignIn />},
	{ path: "/signin", element: <SignIn />},
	{ path: "/sign-up", element: <SignUp />},
	{ path: "/signup", element: <SignUp />},
	{ path: "/supplier-dashboard", element: <SupplierDashboard />},
	{ path: "/supplierdashboard", element: <SupplierDashboard />},
	{ path: "/supplier-product-add", element: <SupplierProductAdd />},
	{ path: "/supplierproductadd", element: <SupplierProductAdd />},
	{ path: "/supplier-product-edit", element: <SupplierProductEdit />},
	{ path: "/supplierproductedit", element: <SupplierProductEdit />},

];
